### ISSUE TITLE
[BUG] No longer usinging a pocket wish to fight embezzlers when we can't clover

### ISSUE THREAD

**Issue by thingolober** [loathers/garbage-collector#1806]
**Describe the bug**
In my run of garbo post CS, after the ween merge garbo will attempt to use a clover to fight an embezzler instead of a pocket wish. I don't have access to clover an embezzler, so I stay lucky the whole time and none of my copies are used. Before this merge garbo used pocket wishes correctly

**To Reproduce**
Don't have access to a lucky embezzler (or locket/any other preferred sources) and run garbo while the clover condition would return true otherwise. Relevant part of my log attached
[temp_embezzler_fail_log.txt](https://github.com/loathers/garbage-collector/files/14074758/temp_embezzler_fail_log.txt)

**Expected behavior**
Garbo uses a pocket wish instead of a clover for an embezzler fight if you can't access embezzlers

**Additional context**
Pretty sure this is the offending line, https://github.com/loathers/garbage-collector/blob/85c23872c0766e8ae75a7eb4b2be8ba7679aff15/packages/garbo/src/embezzler/fights.ts#L884 which should be `===`

**Comment by VuvuzelaVirtuoso** [comment]
[Vuvuzela_Virtuoso_postCS_lucky.txt](https://github.com/loathers/garbage-collector/files/14088176/Vuvuzela_Virtuoso_postCS_lucky.txt)

Adding a snippet of this happening in my log as well--I experienced this bug on the 25th, during the only CS aftercore I've been in since January 4th. Issue has also been noted noted as happening in the same way by Borzon (#2348974) elsewhere.
