### ISSUE TITLE
Breaking at "Executing Non Barf Turn/Lava Dogs (sober)"  [BUG]

### ISSUE THREAD

**Issue by capncastom** [loathers/garbage-collector#1953]
Past couple days, garbo (`garbo ascend` in particular) has broken w/ around 13 advs left when it hits `Executing Non Barf Turn/Lava Dogs (sober)`

Boarding up the doghouse or manually adventuring until getting the volcoino will allow garbo to resume, so doggie code seems suspect.

I saw this pull request, which I assume is what addresses the issue?
https://github.com/loathers/garbage-collector/pull/1952

If not, I can provide debug logs or other helpful info.
Thanks!

**Comment by horrible-little-slime** [comment]
It won't address that issue! It's a stylistic change only! Provide those session logs!

**Comment by horrible-little-slime** [comment]
I was able to recreate the debug error by asking mafia to evaluate `toJson({ x: undefined })`. It looks like part of the problem is passing `{ offhand: undefined }` into `freeFightOutfit` rather than passing just `{}`.

I wasn't able to recreate this error using code from `Outfit.from`, `computeOutfitSpec`, or `validateGarbageFoldable`, so it seems we're passing right through those properly. It's weird, though--it should be virtually impossible to fail to construct an outfit from an empty spec.

**Comment by horrible-little-slime** [comment]
Oh, the outfit doesn't _need_ to throw an error for that code to be called. Alright I'll fix it right now.

**Comment by capncastom** [comment]
worked great, thanks so much !
