### ISSUE TITLE
[FEATURE] 'Resined' support

### ISSUE THREAD

**Issue by Arashmin** [loathers/garbage-collector#2054]
**Is your feature request related to a problem? Please describe.**
The Resined effect, via distilled resin made through inflammable leaves at Your Pile of Burning Leaves (should you have one), is a leaf-positive, and therefore meat-positive, effect.  Autmunal aegis smash for 4 nugs or a wad, guaranteeing each 66 leaves gathered gives an autosell of at least 90-240 meat, and wads are generally worth more.

**Describe the solution you'd like**
Support to automatically top up Resined throughout the day.  If there is support for custom moods with garbo I'm missing though, that could also work

**Describe alternatives and complications**
As mentioned, custom mood adjustments could fix for this probably, but I'm not sure of the support there

**Additional context**
Appreciate the work!

**Comment by horrible-little-slime** [comment]
We already support and use resined

**Comment by Arashmin** [comment]
Odd, didn't seem to see it come up in my logs.  I'll have to take a closer
look.

**Comment by horrible-little-slime** [comment]
https://github.com/loathers/garbage-collector/blob/ba42cd9875eb5dfd6fddaf6dead60d102b64878f/packages/garbo/src/tasks/post/index.ts#L302-L313

This is the code that currently performs it--if you don't have a starting critical mass of leaves (75), and leaves are too inexpensive for you to ever equip the rake, maybe you're just never using it? Or maybe you aren't noticing it because it runs out by EOD on ascension days?

**Comment by Arashmin** [comment]
Reviewing my logs, I did find multiple days of it not being used.  That
said, it looks like it's now using it.  I also see it wasn't buying day
shorteners for a while.

I'm going to chak this up to the Aug4 pref reset issue.  I should have
preserved some logs from before then, but deleted them all when
troubleshooting.  Visiting the campfire manually probably was the fix.
Going to have to keep the manual pref checks in mind if/when this happens
again.

Thanks for the support!
