### ISSUE TITLE
[user friendliness] a "garbo advice" command

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#741]
we very consistently get people coming into #garbage-collector and asking what items they should buy or what things they should look into that would be helpful for garbo or pay out in a reasonable time horizon. it would be great if we could run something like "garbo advice" that would first display this ascii art:
```               ____________________
              |                    |
              |        GARBO       |
              |      ADVICE!       |
              |____________________|
              ||  ,-..'``.        ||
              || (,-..'`. )       ||
              ||   )-c - `)\      ||
,.,._.-.,_,.,-||,.(`.--  ,`',.-,_,||.-.,.,-,._.
           ___||____,`,'--._______||
          |`._||______`'__________||
          |   ||     __           ||
          |   ||    |.-' ,|-      ||
_,_,,..-,_|   ||    ._)) `|-      ||,.,_,_.-.,_
         . `._||__________________||   ____    .
  .              .           .     . <.____`>
.SSt  .      .     .      .    .   _.()`'()`'  .
```
and then display items they could buy that garbo will not buy for them that could improve future usage of garbo as a tool for their account. we could also use projected embezzler value to create high-variance estimates of IOTM impact, but that is very much a future-looking feature, i think a very quick patch would be for things like fishy pipe, jokester's gun, etc.

**Comment by horrible-little-slime** [comment]
LGR, cheeng, thumb ring, pointer ring with an asterisk, pinky ring with a smaller asterisk, shotglass

**Comment by pstalcup** [comment]
I would like if we could have a way in the code inline to register pieces of advice, to make maintenance easier (e.g. if we remove Fishy for some reason the advice doesn't have bad advice about getting a Fishy pipe)

**Comment by docrostov** [comment]
that sounds like hell to me but if we can figure out a slick way to do it that doesn't make garbo advice a pain in the ass to add things to i'm all for it.

**Comment by docrostov** [comment]
my thought is that most (if not all) things in this script can be measured by one of three metrics:

- raw meat it gains per day
- # of embezzlers you gain by doing this
- # of marginal barf turns you gain by doing this

valuation of resources in garbo advice should be based on garbo's understanding of what (roughly) this person's resources will look like for the last embezzlers / last barf turns to calculate these things. things should not show up if they are not profitable at prices; so, for instance, if sand dollars are suddenly 100k garbo should not recommend buying a fishy pipe.

**Comment by libraryaddict** [comment]
Mildly surprised this issue has no further comments. But I'm going to add my own two unwanted cents.


I think the advice can probably be split into multiple sections.

- Barf farming, so raising the MPA doing barf. Not the digitized or the like. This would be checking for items that raise the value of a single adventure. So if we spend a single turn in barf every day, anything that would improve our mpa goes here.
- Pre-Barf, this is the stuff like backup camera or whatnot.
- Whole day. This is stuff like pantsgiving, digitizing, etc. Stuff that are useful if we're running a full day of barf.

Each of these sections are split into two. Accessible for a cheap account, and expensive stuff, like iotms. If you want to get fancy, you can include the prices and the potential meat gain for getting this.

I don't think its worth the headache of calculating the meat gain of multiple items combined. Just do a simple disclaimer: These are estimates and we don't recommend buying the expensive stuff without some research.

As for equipment, just have three different sections. Equipment that can be brought. Equipment that must be earned. Equipment thats an iotm.

And hardcode it I suppose. Don't bother running maximizer on the equipment, since assume I pick up some equips it recommends and I pick up some other stuff it recommends. But maximizer now knows I can hit a higher MPA since I now have this familiar. So it recommends different equipment instead.

**Comment by horrible-little-slime** [comment]
Frankly, I am not super jazzed about the idea of recommending people buy
items of limited supply for meat farming. Besides the fact that they will
almost never be profitable, it bums me out when old items have their prices
rise, and I'd personally rather that old rares be put towards ascension and
shenanigans, as opposed to the perpetual toil of barf.

It feels a little hypocritical to say that, given the way I play. But
that's life baby.

**Comment by horrible-little-slime** [comment]
This is partially obsoleted by items.md

**Comment by docrostov** [comment]
closing this because i agree with the czar of garbo and with the existence of items.md it just isn't needed
